[package]
name = "sm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "9.0.2"
wasmtime-wasi = "9.0.2"
criterion = "0.5.1"

[[bench]]
name = "js"
harness = false
